package com.example.healthapp.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents a doctor's checkup or appointment for a user.
 *
 * @property id The unique identifier for the checkup. Auto-generated by the database.
 * @property userId The ID of the user this checkup belongs to.
 * @property date The timestamp of the checkup appointment.
 * @property doctorName The name of the doctor for the checkup.
 * @property location The location of the checkup (e.g., hospital name, clinic address).
 * @property notes Any additional notes about the checkup.
 */
@Entity(tableName = "checkups",
    foreignKeys = [ForeignKey(entity = User::class,
        parentColumns = ["id"],
        childColumns = ["userId"],
        onDelete = ForeignKey.CASCADE)])
data class Checkup(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val userId: Int,
    val date: Long,
    val doctorName: String,
    val location: String,
    val notes: String
)
