package com.example.healthapp.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents a single health metric reading for a user.
 *
 * @property id The unique identifier for the health metric. Auto-generated by the database.
 * @property userId The ID of the user this metric belongs to.
 * @property date The timestamp when the metric was recorded.
 * @property bloodPressure The user's blood pressure at the time of recording (e.g., "120/80").
 * @property bloodSugar The user's blood sugar level at the time of recording (e.g., "90 mg/dL").
 * @property heartRate The user's heart rate at the time of recording (e.g., "70 bpm").
 * @property notes Any additional notes about the health metric reading.
 */
@Entity(tableName = "health_metrics",
    foreignKeys = [ForeignKey(entity = User::class,
        parentColumns = ["id"],
        childColumns = ["userId"],
        onDelete = ForeignKey.CASCADE)])
data class HealthMetric(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val userId: Int,
    val date: Long,
    val bloodPressure: String,
    val bloodSugar: String,
    val heartRate: String,
    val notes: String
)
