package com.example.healthapp.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a medication that a user needs to take.
 *
 * @property id The unique identifier for the medication. Auto-generated by the database.
 * @property userId The ID of the user this medication belongs to.
 * @property name The name of the medication.
 * @property dosage The dosage of the medication (e.g., "1 tablet", "10mg").
 * @property frequency How often the medication should be taken (e.g., "Once a day").
 * @property time A comma-separated string of times when the medication should be taken (e.g., "08:00,20:00").
 * @property stock The current number of pills/doses remaining.
 * @property lowStockThreshold The threshold at which to warn the user about low stock.
 */
@Entity(tableName = "medications",
    foreignKeys = [ForeignKey(entity = User::class,
        parentColumns = ["id"],
        childColumns = ["userId"],
        onDelete = ForeignKey.CASCADE)])
data class Medication(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val userId: Int,
    val name: String,
    val dosage: String,
    val frequency: String,
    val time: String, // e.g., "08:00,12:00,20:00"
    var stock: Int,
    val lowStockThreshold: Int
)
