package com.example.healthapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user in the application.
 *
 * @property id The unique identifier for the user. Auto-generated by the database.
 * @property username The user's chosen username. Must be unique.
 * @property passwordHash The salted and hashed password for the user.
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val username: String,
    val passwordHash: String
)
